#ifndef IDT_H
#define IDT_H

#include <stdint.h>


/*
 * ============================================================
 * Interrupt register frame
 * ============================================================
 *
 * This must exactly match the stack layout generated by
 * kernel/idt.s after pusha.
 *
 * Stack:
 *
 *   edi
 *   esi
 *   ebp
 *   esp
 *   ebx
 *   edx
 *   ecx
 *   eax
 *   int_no
 *   err_code
 *   eip
 *   cs
 *   eflags
 */
struct registers
{
    uint32_t edi;
    uint32_t esi;
    uint32_t ebp;
    uint32_t esp;

    uint32_t ebx;
    uint32_t edx;
    uint32_t ecx;
    uint32_t eax;

    uint32_t int_no;
    uint32_t err_code;

    uint32_t eip;
    uint32_t cs;
    uint32_t eflags;
};


/*
 * ============================================================
 * IDT initialization
 * ============================================================
 */
void idt_init(void);


/*
 * ============================================================
 * Interrupt dispatcher
 * ============================================================
 *
 * Returns the interrupt frame that the assembly ISR must
 * restore.
 *
 * Usually this is the current frame.
 *
 * During task scheduling, this may be the saved frame of
 * another task.
 */
struct registers *isr_handler(
    struct registers *regs
);


#endif /* IDT_H */
